--MemberDao.getMember(int page)
SELECT * FROM MEMBERS;

SELECT * FROM (SELECT ROWNUM NUM, MEMBERS.*FROM MEMBERS) WHERE NUM BETWEEN 1 AND 10;

SELECT * FROM (SELECT ROWNUM NUM, MEMBERS.*FROM MEMBERS) WHERE NUM BETWEEN 11 AND 20;

SELECT * FROM MEMBERS ORDER BY NAME;
SELECT * FROM MEMBERS ORDER BY REGDATE;

SELECT * FROM (SELECT * FROM MEMBERS ORDER BY NAME)

SELECT C##SIST.MEMBERS.MID, C##SIST.MEMBERS.NAME, C##SIST.MEMBERS.GENDER,
  C##SIST.NOTICES.TITLE, C##SIST.NOTICES.REGDATE
  FROM
       C##SIST.MEMBERS JOIN C##SIST.NOTICES ON C##SIST.MEMBERS.MID = C##SIST.NOTICES.CODE

       
 SELECT * FROM (SELECT ROWNUM NUM, C##SIST.MEMBERS.* FROM C##SIST.MEMBERS ORDER BY REGDATE) WHERE NUM BETWEEN 2 AND 10;
 
 SELECT * FROM (SELECT ROWNUM NUM, MEMBERS.*FROM MEMBERS(SELECT * FROM MEMBERS ORDER BY REGDATE)) 
 																										WHERE NUM BETWEEN 11 AND 20;

 --rownum!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 SELECT * FROM (SELECT ROWNUM NUM, A.*FROM (SELECT * FROM MEMBERS ORDER BY REGDATE) A) WHERE NUM BETWEEN 11 AND 20;
 
 --MemberDao.getMembers(int page)
 SELECT * FROM
(
	SELECT ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM, MEMBERS.*FROM MEMBERS
)A WHERE NUM BETWEEN 1 AND 10;


